version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node # cimg/base:stable
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          working_directory: react/react-docker
          command: yarn install
      - run:
          working_directory: react/react-docker
          command: yarn build
      - run:
          working_directory: react/react-docker
          command: yarn start
      - run:
          working_directory: react/react-docker
          command: npm test
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build # say-hello
# orbs:
#   node: circleci/node@4.2.1

# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: docker
#     steps:
#       - setup_remote_docker:
#           docker_layer_caching: true
#       - run: docker image ls
#       - run: docker volume ls
#       - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
#       - run: docker volume ls

# workflows:
#   app-tests:
#     jobs:
#       - build
